clear; clc; close all;
mouseNameList = {'M1_102721', 'M2_102821','M3_102921',...
    'M5_120221'};
% dataPathPrefix = 'E:\Ephys\Conc_Series';
dataPathPrefix = 'D:\Reza\sniffOdorProject\Conc_Series';

%%
[tBeginning, tEnd, trialsToRemove]=...
    get_removal_variables();
add_ndt_paths_and_init_rand_generator
conc_set = [1,2,4];
numberOfBalanceSampling = 100;
%%
pltDir = fullfile(final_figs_path('uniTn1'),...
    'Fig5_A');
if ~exist(pltDir , 'dir')
   mkdir(pltDir)
end
[colorSet, SandR_colors] =...
    set_plot_seting(15, 8);
%%
exp_vars = nan(50, numberOfBalanceSampling);
for perm = 1: numberOfBalanceSampling
    [fSpaceCell, ~] =...
        get_aSample(dataPathPrefix, mouseNameList,....
                    conc_set, 1:2, tBeginning, tEnd,trialsToRemove,...
                    1, 1, 6, .5);
    pseudoPopulation = [fSpaceCell{1}, fSpaceCell{2},fSpaceCell{3}, fSpaceCell{4}];
    [~,~,latent] = pca(zscore(pseudoPopulation));
    exp_vars(:, perm) = latent(1:50);
end
exp_vars_mean = mean(exp_vars, 2);
exp_vars_std = std(exp_vars,[], 2);
%%
close all;
figure;
hold on
numOfDime = 15;
plot(cumsum(exp_vars_mean(1:numOfDime))/sum(exp_vars_mean)*100,'LineWidth',2.5)
exVarByEachPCTr = [];
for PCi = 1 : numOfDime
    exVarByEachPCTr = [exVarByEachPCTr,...
        exp_vars_mean(PCi)/sum(exp_vars_mean)*100];
end
bar(1:numOfDime, exVarByEachPCTr, 'b')
ylabel('Eplained var(%)')
xlim([.5,numOfDime+.5])
ylim([0,70])
xlabel('# PC')
xticks([1:15])
set(gcf,'Position',[200,200,500,300]);
print_it(pltDir, 'eplend_var', 'pooled')
%%
file_id = fopen(fullfile(pltDir, 'var_explained_by_PCs.txt'),'w');
for PCi = 1 : numOfDime
    fprintf(file_id, 'PC %d = %.2f %% \n',...
        PCi, exVarByEachPCTr(PCi));
end
fclose(file_id);
%%
[fSpaceCell, fSpaceLbelsCell] =...
    get_aSample(dataPathPrefix, mouseNameList,....
                conc_set, 1:2, tBeginning, tEnd,trialsToRemove,...
                2.5, 1, 6, .5);
pseudoPopulation = [fSpaceCell{1}, fSpaceCell{2},fSpaceCell{3}, fSpaceCell{4}];
[~,score,~] = pca(zscore(pseudoPopulation));
fSpaceLbels = fSpaceLbelsCell{1};
%%-
axisLim = [-12,14];
markerSize = 20;
markerFaceAlpha = [.3,.6,0,.9];
markerEdgeAlpha = [.3,.6,0,.9];
for odorId = 1 : max(fSpaceLbels.OdorId ) 
    f1 = figure;
    hold on 
    for ci = conc_set
        scatter((score( fSpaceLbels.RespLabel == 2 &...
            fSpaceLbels.ConcId == ci & fSpaceLbels.OdorId == odorId , 1)),...
             (score(fSpaceLbels.RespLabel ==2 &...
             fSpaceLbels.ConcId== ci & fSpaceLbels.OdorId == odorId, 2)),...
             markerSize, 'MarkerEdgeColor',SandR_colors.r,...
             'MarkerFaceColor',SandR_colors.r,...
            'MarkerFaceAlpha',markerFaceAlpha(ci),...
            'MarkerEdgeAlpha',markerEdgeAlpha(ci));
        scatter((score( fSpaceLbels.RespLabel == 1 &...
            fSpaceLbels.ConcId == ci & fSpaceLbels.OdorId == odorId , 1)),...
             (score(fSpaceLbels.RespLabel == 1 &...
             fSpaceLbels.ConcId== ci & fSpaceLbels.OdorId == odorId, 2)),...
             markerSize, 'MarkerEdgeColor',SandR_colors.s,...
             'MarkerFaceColor',SandR_colors.s,...
            'MarkerFaceAlpha',markerFaceAlpha(ci),...
            'MarkerEdgeAlpha',markerEdgeAlpha(ci));
    end
    scatter((score(fSpaceLbels.OdorId ==0 & fSpaceLbels.RespLabel==2, 1)),...
         (score(fSpaceLbels.OdorId ==0 & fSpaceLbels.RespLabel==2, 2)),...
         markerSize, 'MarkerEdgeColor',SandR_colors.r,...
         'MarkerFaceColor',SandR_colors.r,...
        'LineWidth', 1.3, 'MarkerFaceAlpha',0,'MarkerEdgeAlpha',1);
    scatter((score(fSpaceLbels.OdorId ==0 & fSpaceLbels.RespLabel==1, 1)),...
         (score(fSpaceLbels.OdorId ==0 & fSpaceLbels.RespLabel==1, 2)),...
         markerSize, 'MarkerEdgeColor',SandR_colors.s,...
         'MarkerFaceColor',SandR_colors.s,...
        'LineWidth', 1.3, 'MarkerFaceAlpha',0,'MarkerEdgeAlpha',1);
    set(gca,'LineWidth',2)
    xlabel('PC 1'); ylabel('PC 2');
    xlim(axisLim); ylim(axisLim)
    title({sprintf('odor %d - pseudo population',odorId), ''})
    box off
    axis square
    set(gcf,'Position',[50,50,450,450]);
    %%
    print_it(pltDir, sprintf('odor%d_2D_PCA',odorId), 'pseudoPopulation')
end
%% -
for mn = 1 : length(mouseNameList)
    totalSpace = fSpaceCell{mn};
    [coeff,score,latent] = pca(zscore(totalSpace));
    fSpaceLbels = fSpaceLbelsCell{mn};
    %%

    markerSize = 25;
    markerFaceAlpha = .15:.28:1;
    markerEdgeAlpha = .15:.28:1;
    for odorId = 1 : max(fSpaceLbels.OdorId )
        close all
         f1 = figure;
        hold on 
        for ci = conc_set
            scatter((score( fSpaceLbels.RespLabel == 2 &...
                fSpaceLbels.ConcId == ci & fSpaceLbels.OdorId == odorId , 1)),...
                 (score(fSpaceLbels.RespLabel ==2 &...
                 fSpaceLbels.ConcId== ci & fSpaceLbels.OdorId == odorId, 2)),...
                 markerSize, 'MarkerEdgeColor',SandR_colors.r,...
                 'MarkerFaceColor',SandR_colors.r,...
                'MarkerFaceAlpha',markerFaceAlpha(ci),...
                'MarkerEdgeAlpha',markerEdgeAlpha(ci));
            scatter((score( fSpaceLbels.RespLabel == 1 &...
                fSpaceLbels.ConcId == ci & fSpaceLbels.OdorId == odorId , 1)),...
                 (score(fSpaceLbels.RespLabel == 1 &...
                 fSpaceLbels.ConcId== ci & fSpaceLbels.OdorId == odorId, 2)),...
                 markerSize, 'MarkerEdgeColor',SandR_colors.s,...
                 'MarkerFaceColor',SandR_colors.s,...
                'MarkerFaceAlpha',markerFaceAlpha(ci),...
                'MarkerEdgeAlpha',markerEdgeAlpha(ci));
        end
        scatter((score(fSpaceLbels.OdorId ==0 & fSpaceLbels.RespLabel==2, 1)),...
             (score(fSpaceLbels.OdorId ==0 & fSpaceLbels.RespLabel==2, 2)),...
             markerSize, 'MarkerEdgeColor',SandR_colors.r,...
             'MarkerFaceColor',SandR_colors.r,...
            'LineWidth', 1.3, 'MarkerFaceAlpha',0,'MarkerEdgeAlpha',1);
        scatter((score(fSpaceLbels.OdorId ==0 & fSpaceLbels.RespLabel==1, 1)),...
             (score(fSpaceLbels.OdorId ==0 & fSpaceLbels.RespLabel==1, 2)),...
             markerSize, 'MarkerEdgeColor',SandR_colors.s,...
             'MarkerFaceColor',SandR_colors.s,...
            'LineWidth', 1.3, 'MarkerFaceAlpha',0,'MarkerEdgeAlpha',1);
        set(gca,'LineWidth',2)
        xlabel('PC 1'); ylabel('PC 2');
        title({sprintf('odor %d - mouse %d',odorId, mn), ''})
        box off
        axis square
        set(gcf,'Position',[50,50,450,450]);
        print_it(pltDir, sprintf('odor%d_2D_PCA',odorId), mouseNameList{mn})
    end
end