clear; clc; close all;

dataDir = fullfile('G:\My Drive\sinff-odor-project',....
    'Figuers_data_Marh2023');

[colorSet, SandR_colors] = set_plot_seting(15, 4);
pltDir = fullfile(final_figs_path('uniTn1'),...
    'fig5_H_I-same_size_sample_fixation');
if ~exist(pltDir , 'dir')
   mkdir(pltDir)
end
fileDir = pltDir;
load(fullfile(dataDir, 'fig5_H_I_high_correlated_sub_units_data_same_size_fixation',...
    'fig5_H_I_high_correlated_sub_units_data'));
%%
linseSizePLT = 2.5;

for sc = [1,2]        
    for sId = 1
        for oId = 1 : 2
            %%
            close all;
            f1 = figure;
            hold on
            p  = plot([0 30],[100/3,100/3],...
                    'linestyle','-.','Color','k');
            errorbar(0,...
                nanmean(squeeze(decodingAcc_Mix(:, sId, oId, sc, :)),[1,2]),...
                nanstd(squeeze(decodingAcc_Mix(:, sId, oId, sc, :)),[],[1,2]),...
                'Marker', 'o', 'Color', colorSet(1,:),...
                'CapSize', 3, 'LineWidth', linseSizePLT, 'MarkerSize', 4)
            errorbar(1,...
                nanmean(squeeze(decodingAcc_R(:, sId, oId, sc, :)),[1,2]),...
                nanstd(squeeze(decodingAcc_R(:, sId, oId, sc, :)),[],[1,2]),...
                'Marker', 'o', 'Color', colorSet(1,:),...
                'CapSize', 3, 'LineWidth', linseSizePLT, 'MarkerSize', 4)
            errorbar(2,...
                nanmean(squeeze(decodingAcc_S(:, sId, oId, sc, :)),[1,2]),...
                nanstd(squeeze(decodingAcc_S(:, sId, oId, sc, :)),[],[1,2]),...
                'Marker', 'o', 'Color', colorSet(1,:),...
                'CapSize', 3, 'LineWidth', linseSizePLT, 'MarkerSize', 4)
            errorbar(3,...
                nanmean(squeeze(decodingAcc_Strain_Rtest(:, sId, oId, sc, :)),[1,2]),...
                nanstd(squeeze(decodingAcc_Strain_Rtest(:, sId, oId, sc, :)),[],[1,2]),...
                'Marker', 'o', 'Color', colorSet(1,:),...
                'CapSize', 3, 'LineWidth', linseSizePLT, 'MarkerSize', 4)
           errorbar(4,...
                nanmean(squeeze(decodingAcc_Rtrain_Stest(:, sId, oId, sc, :)),[1,2]),...
                nanstd(squeeze(decodingAcc_Rtrain_Stest(:, sId, oId, sc, :)),[],[1,2]),...
                'Marker', 'o', 'Color', colorSet(1,:),...
                'CapSize', 3, 'LineWidth', linseSizePLT, 'MarkerSize', 4)

            errorbar(0+1/4,...
                nanmean(squeeze(decodingAcc_Mix(:, sId, oId, 3, :)),[1,2]),...
                nanstd(squeeze(decodingAcc_Mix(:, sId, oId, 3, :)),[],[1,2]),...
                'Marker', 'o', 'Color', colorSet(2,:),...
                'CapSize', 3, 'LineWidth', linseSizePLT, 'MarkerSize', 4)
            errorbar(1+1/4,...
                nanmean(squeeze(decodingAcc_R(:, sId, oId, 3, :)),[1,2]),...
                nanstd(squeeze(decodingAcc_R(:, sId, oId, 3, :)),[],[1,2]),...
                'Marker', 'o', 'Color', colorSet(2,:),...
                'CapSize', 3, 'LineWidth', linseSizePLT, 'MarkerSize', 4)
            errorbar(2+1/4,...
                nanmean(squeeze(decodingAcc_S(:, sId, oId, 3, :)),[1,2]),...
                nanstd(squeeze(decodingAcc_S(:, sId, oId, 3, :)),[],[1,2]),...
                'Marker', 'o', 'Color', colorSet(2,:),...
                'CapSize', 3, 'LineWidth', linseSizePLT, 'MarkerSize', 4)
            errorbar(3+1/4,...
                nanmean(squeeze(decodingAcc_Strain_Rtest(:, sId, oId, 3, :)),[1,2]),...
                nanstd(squeeze(decodingAcc_Strain_Rtest(:, sId, oId, 3, :)),[],[1,2]),...
                'Marker', 'o', 'Color', colorSet(2,:),...
                'CapSize', 3, 'LineWidth', linseSizePLT, 'MarkerSize', 4)
           errorbar(4+1/4,...
                nanmean(squeeze(decodingAcc_Rtrain_Stest(:, sId, oId, 3, :)),[1,2]),...
                nanstd(squeeze(decodingAcc_Rtrain_Stest(:, sId, oId, 3, :)),[],[1,2]),...
                'Marker', 'o', 'Color', colorSet(2,:),...
                'CapSize', 3, 'LineWidth', linseSizePLT, 'MarkerSize', 4)
            
            
            yticks([25, 50,75,100])
            xticks(1:4);
            xticklabels({'R-type', 'S-type',...
                'S-train/R-test', 'R-train/S-test'})
            xtickangle(45)
            box off
            xlim([.5,4.5])
            ylim([20, 102])
            ylabel('accuracy(%)')
            set(gcf,'Position',[120,120,270,400]);
            
            status = [];
            if sc == 1
               status = 'negatively correlated';
            elseif sc == 2
                status = 'positively correlated';
            end
            if sId == 1               
                title({sprintf('Conc. decoding, odro %d', oId),...
                    sprintf('%s', status), 'full Space.'})
                
                print_it(pltDir, sprintf('fullSpace_Odor_%d_%s',...
                    oId, status), 'pooled')
            elseif sId == 2
                title({sprintf('Conc. decoding, odro %d', oId),...
                    sprintf('%s', status), '2D proj.'})
                print_it(pltDir, sprintf('2D_proj_Odor_%d_sc_%d',...
                    oId, sc), 'pooled')
            end
            %%
        end
    end
end